name: Sample Workflow

on:
  push:
  workflow_dispatch:

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest

    steps:
      - name: string
        run: echo "Welcome from CI/CD training!"

      - name: multiline scripts
        run: |
          node -v
          npm -v
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python
